### ISSUE TITLE
Duplicated info in extra table

### ISSUE THREAD

**Issue by jovimon** [beave/barnyard2-extra#1]
I've detected that sometimes extra data regarding the same alert (i.e. same sid-cid pair) is inserted 2+ times. 
For example:

> id, sid, cid, type, datatype, len, data
> 34, 1, 98, 9, 1, 459, example.com/examplepage.html
> 35, 1, 98, 10, 1, 36, example.com
> 36, 1, 98, 9, 1, 459, example.com/examplepage.html
> 37, 1, 98, 10, 1, 36, example.com

**Comment by beave** [comment]
Hmmmm..  Let me see if i can reproduce.

**Comment by beave** [comment]
We run this at a lot of sites and are not seeing this.  Could this have been fixed in a later release?  Let me know.  Otherwise, I'm going to close this.
