### ISSUE TITLE
Extra data placed on the wrong event

### ISSUE THREAD

**Issue by jovimon** [beave/barnyard2-extra#2]
Hello,

I'm seeing odd behaviour in my alerts and discovered that some extra data fields are being placed on the wrong alerts. Using u2spewfoo tool from snort package to check unified2 files, I discovered that problem is probably in barnyard2-extra side.

Alerts usually are like this one (some info redacted):

```
(Event)
        sensor id: 0    event id: 666666        event second: 1464777969        event microsecond: 879
        sig id: 9999999 gen id: 1       revision: 3      classification: 21
        priority: 1     ip source: aaa.bbb.ccc.ddd      ip destination: ddd.ccc.bbb.aaa
        src port: 2894  dest port: 5943 protocol: 6     impact_flag: 0  blocked: 0

Packet
        sensor id: 0    event id: 666666        event second: 1464777969
        packet second: 1464777969       packet microsecond: 879
        linktype: 1     packet_length: 97
[    0] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[   16] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[   32] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[   48] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[   64] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[   80] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[   96] 00                                               .
```

When some extra data appears, it looks like this (some info redacted):

```
(ExtraDataHdr)
        event type: 4   event length: 36

(ExtraData)
        sensor id: 0    event id: 777777        event second: 1464774349
        type: 1 datatype: 1     bloblength: 12  Original Client IP: 172.16.50.255

(ExtraDataHdr)
        event type: 4   event length: 270

(ExtraData)
        sensor id: 0    event id: 777777        event second: 1464774349
        type: 9 datatype: 1     bloblength: 246 HTTP URI: /this-is-some-random-url-as-shown-in-extra-data-events

(ExtraDataHdr)
        event type: 4   event length: 50

(ExtraData)
        sensor id: 0    event id: 777777        event second: 1464774349
        type: 10        datatype: 1     bloblength: 26  HTTP Hostname: google.com
```

The problem is that when this extra data info appear, it is attached to the event that appears right before it on the file, even if the id of the event and the id of the extra data do not match.

So, if I have this sequence of data in my unified file:

> Alert 1
> ExtraData 1
> Alert 2
> Alert 3
> Alert 4
> ExtraData 3
> Alert 5

ExtraData 1 is correctly assigned to Alert 1 but ExtraData 3 appears in Alert 4 instead of in Alert 3.

The sensors where I'm having this behaviour are under heavy load, so maybe this is what is generating out of order unified2 files. Anyway, barnyard2 should be able to handle this.

Hope you can help.

Regards,

Jose.

**Comment by CyberTaoFlow** [comment]
^bump

**Comment by beave** [comment]
Sorry,  havent had a chance to look into this.  It's not forgotten.....

**Comment by CyberTaoFlow** [comment]
i will test as well

**Comment by bhennigar** [comment]
Checking to see if there's been any progress on this. Thanks!

**Comment by beave** [comment]
That fix didnt' work, btw..  re-looking into this.

**Comment by beave** [comment]
This project has been abandon.   If you are using Barnyard2-extra for Sagan or Suricata,  I highly suggest checking out https://github.com/beave/meer .  It'll work a lot better for you.  Good luck and thanks!
